server:
  port: 5000
spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
        - id: user-consumer
          uri: http://localhost:8893
          predicates:
            - Path=/api-u/**
          filters:
            - RewritePath=/api-u/(?<segment>.*),/$\{segment}
        - id: b2b-goods-consumer
          uri: http://localhost:8896
          predicates:
            - Path=/api-g/**
          filters:
            - RewritePath=/api-g/(?<segment>.*),/$\{segment}
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8500/eureka/