server:
  port: 8601
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/b2bdata?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: b2b-user-provider
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:8500/eureka/
  instance:
    hostname: localhost
mybatis:
  mapper-locations: classpath:/mapper/*